### ISSUE TITLE
Media keys, Volume, and mouse keys do not function

### ISSUE THREAD

**Issue by jeffvandyke** [fd0/ergodox-tmk#1]
Just finished my new Ergodox, and my old firmware works fine, but I love the improvements in this project like nearly-instant N-key rollover, no need to power-cycle keyboard during computer boot time, better project structure, etc... Congrats!

I tried the built-in configuration with some of my old keys such as volume up, media play, etc., but they don't seem to be registering. Have you managed to get these keys to work?
(examples: `MUTE, VOLD, VOLU, MPRV, MPLY, MNXT, MS_U, MS_D, MS_L, MS_R`)

**Comment by jeffvandyke** [comment]
For more info on these keys not working, I tried (from tty2 in Linux (Ctrl-Alt-2)) to use showkeys --scancodes, and while all the other keys worked, the unfunctional keys didn't register any scancodes.

**Comment by jeffvandyke** [comment]
Nevermind, config issue, I think I'll make a pull request for this...

**Comment by fd0** [comment]
Ok, cool. I'm glad my code helped you, I was a bit annoyed with the original code and dug in to improve it ;)
